= Imperium
:keywords: ati, data, big-data-ecosystem-core

== Overview

Imperium adalah sebuah _Big Data project_ yang mengusung konsep _service-oriented_ dan berbasis _cloud computing_, Imperium hadir karena kebutuhan akan data sangat tinggi dan semakin kompleks.
Sebagai _data platform_, Imperium menggunakan teknologi dari Google yaitu Google Cloud Platform karena lebih unggul dalam banyak hal, diantaranya :

* Security
* Multi-Cloud
* Server less
* Integrated with open source software
* AI and machine learning
* Cheap and easy to implemented

== Background

Seiring semakin banyaknya bisnis yang didorong oleh data (data-driven), ada kebutuhan yang semakin besar untuk melaksanakan "`pipa`" pemrosesan data (data pipeline) yang kompleks dan yang secara teratur mengekstraksi data dari berbagai sumber structured dan non structured, mengubah data menjadi format yang memfasilitasi logika bisnis, dan menyimpan value yang dihasilkan dengan cara memfasilitasi peningkatan produk dan pengambilan keputusan stakeholder.
Dengan mempertimbangkan hal tersebut data team berinisiatif untuk meningkatkan service nya dala rangka support data service dengan membuat "Imperium" project.

== How it works?

* Migrasi data dari sepulsa micro-systems ke _datalake_ yang berbasis _google cloud platform_ secara berkala dengan metode ELT untuk diolah menjadi _reporting_ atau _analitics_, untuk _orchestrator_-nya, Imperium menggunakan tehnologi 'Apache Airflow' untuk menggantikan pekerjaan yang sebelumnya di-_handle_ oleh sistem Buffalo.
* Menyediakan serangkaian layanan _cloud modular_ termasuk komputasi, penyimpanan data, analisis data dan _machine learning_.

== Team Involved

|===
| *Name*  | *Role* | *Email*    
 
| Bayu Setiawan
| Product Owner 
| bayu@alterra.id

| Bayu Setiawan 
| Lead Data Engineer  
| bayu@alterra.id

| Ranu Goldan Yeara 
| Data Engineer 
| ranu@alterra.id

| Vera Rusmalawati 
| Data Engineer  
| vera@alterra.id

| Dimas Ardiyanto
| System Analyst  
| dardiyanto@alterra.id
|===

== Technical Information

<<docs/architecture-imperium.adoc#, Architecture Imperium>>

<<docs/technology-imperium.adoc#, Technology Imperium>>

<<docs/flow-wire-imperium.adoc#, Flow and Wireframe Imperium>>

== Dokumentation 

<<docs/adr-doc-imperium.adoc#, ADR Document Imperium>>

<<docs/product-information-imperium.adoc#, Product Information Document Imperium>>